import type { Metadata } from "next";
import '../app/styles/global.scss'


export const metadata: Metadata = {
  title: "Glamping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang='en'>
			<head>
				<script
					src='https://api-maps.yandex.ru/2.1/?apikey=8b720d79-0321-4fd2-8071-ab267040a6ad&lang=ru_RU'
					type='text/javascript'
				/>
			</head>
			<body className=''>{children}</body>
		</html>
	)
}
